package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Autobusi generated by hbm2java
 */
public class Autobusi  implements java.io.Serializable {


     private Integer id;
     private String marka;
     private String model;
     private int brSedista;
     private String slike;
     private int slobodan;
     private Set medjugradskes = new HashSet(0);

    public Autobusi() {
    }

	
    public Autobusi(String marka, String model, int brSedista, int slobodan) {
        this.marka = marka;
        this.model = model;
        this.brSedista = brSedista;
        this.slobodan = slobodan;
    }
    public Autobusi(String marka, String model, int brSedista, String slike, int slobodan, Set medjugradskes) {
       this.marka = marka;
       this.model = model;
       this.brSedista = brSedista;
       this.slike = slike;
       this.slobodan = slobodan;
       this.medjugradskes = medjugradskes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMarka() {
        return this.marka;
    }
    
    public void setMarka(String marka) {
        this.marka = marka;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public int getBrSedista() {
        return this.brSedista;
    }
    
    public void setBrSedista(int brSedista) {
        this.brSedista = brSedista;
    }
    public String getSlike() {
        return this.slike;
    }
    
    public void setSlike(String slike) {
        this.slike = slike;
    }
    public int getSlobodan() {
        return this.slobodan;
    }
    
    public void setSlobodan(int slobodan) {
        this.slobodan = slobodan;
    }
    public Set getMedjugradskes() {
        return this.medjugradskes;
    }
    
    public void setMedjugradskes(Set medjugradskes) {
        this.medjugradskes = medjugradskes;
    }




}


