package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gradske generated by hbm2java
 */
public class Gradske  implements java.io.Serializable {


     private int brLinije;
     private String polaziste;
     private String odrediste;
     private String medjustanice;
     private Set otkazanes = new HashSet(0);
     private Set vozigradskus = new HashSet(0);
     private Set redvoznjes = new HashSet(0);

    public Gradske() {
    }

	
    public Gradske(int brLinije, String polaziste, String odrediste, String medjustanice) {
        this.brLinije = brLinije;
        this.polaziste = polaziste;
        this.odrediste = odrediste;
        this.medjustanice = medjustanice;
    }
    public Gradske(int brLinije, String polaziste, String odrediste, String medjustanice, Set otkazanes, Set vozigradskus, Set redvoznjes) {
       this.brLinije = brLinije;
       this.polaziste = polaziste;
       this.odrediste = odrediste;
       this.medjustanice = medjustanice;
       this.otkazanes = otkazanes;
       this.vozigradskus = vozigradskus;
       this.redvoznjes = redvoznjes;
    }
   
    public int getBrLinije() {
        return this.brLinije;
    }
    
    public void setBrLinije(int brLinije) {
        this.brLinije = brLinije;
    }
    public String getPolaziste() {
        return this.polaziste;
    }
    
    public void setPolaziste(String polaziste) {
        this.polaziste = polaziste;
    }
    public String getOdrediste() {
        return this.odrediste;
    }
    
    public void setOdrediste(String odrediste) {
        this.odrediste = odrediste;
    }
    public String getMedjustanice() {
        return this.medjustanice;
    }
    
    public void setMedjustanice(String medjustanice) {
        this.medjustanice = medjustanice;
    }
    public Set getOtkazanes() {
        return this.otkazanes;
    }
    
    public void setOtkazanes(Set otkazanes) {
        this.otkazanes = otkazanes;
    }
    public Set getVozigradskus() {
        return this.vozigradskus;
    }
    
    public void setVozigradskus(Set vozigradskus) {
        this.vozigradskus = vozigradskus;
    }
    public Set getRedvoznjes() {
        return this.redvoznjes;
    }
    
    public void setRedvoznjes(Set redvoznjes) {
        this.redvoznjes = redvoznjes;
    }




}


