package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1



/**
 * Koordinate generated by hbm2java
 */
public class Koordinate  implements java.io.Serializable {


     private Integer id;
     private String grad;
     private double latitude;
     private double longitude;

    public Koordinate() {
    }

    public Koordinate(String grad, double latitude, double longitude) {
       this.grad = grad;
       this.latitude = latitude;
       this.longitude = longitude;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGrad() {
        return this.grad;
    }
    
    public void setGrad(String grad) {
        this.grad = grad;
    }
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }




}


