package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Korisnik generated by hbm2java
 */
public class Korisnik  implements java.io.Serializable {


     private String username;
     private String password;
     private int tip;
     private String ime;
     private String prezime;
     private String adresa;
     private Date datumRodj;
     private String telefon;
     private String zaposlenje;
     private String email;
     private int status;
     private Set rezervacijas = new HashSet(0);
     private Set markices = new HashSet(0);

    public Korisnik() {
    }

	
    public Korisnik(String username, String password, int tip, String ime, String prezime, String adresa, Date datumRodj, String telefon, String zaposlenje, int status) {
        this.username = username;
        this.password = password;
        this.tip = tip;
        this.ime = ime;
        this.prezime = prezime;
        this.adresa = adresa;
        this.datumRodj = datumRodj;
        this.telefon = telefon;
        this.zaposlenje = zaposlenje;
        this.status = status;
    }
    public Korisnik(String username, String password, int tip, String ime, String prezime, String adresa, Date datumRodj, String telefon, String zaposlenje, String email, int status, Set rezervacijas, Set markices) {
       this.username = username;
       this.password = password;
       this.tip = tip;
       this.ime = ime;
       this.prezime = prezime;
       this.adresa = adresa;
       this.datumRodj = datumRodj;
       this.telefon = telefon;
       this.zaposlenje = zaposlenje;
       this.email = email;
       this.status = status;
       this.rezervacijas = rezervacijas;
       this.markices = markices;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getTip() {
        return this.tip;
    }
    
    public void setTip(int tip) {
        this.tip = tip;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }
    public Date getDatumRodj() {
        return this.datumRodj;
    }
    
    public void setDatumRodj(Date datumRodj) {
        this.datumRodj = datumRodj;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getZaposlenje() {
        return this.zaposlenje;
    }
    
    public void setZaposlenje(String zaposlenje) {
        this.zaposlenje = zaposlenje;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getRezervacijas() {
        return this.rezervacijas;
    }
    
    public void setRezervacijas(Set rezervacijas) {
        this.rezervacijas = rezervacijas;
    }
    public Set getMarkices() {
        return this.markices;
    }
    
    public void setMarkices(Set markices) {
        this.markices = markices;
    }




}


