package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1



/**
 * Markice generated by hbm2java
 */
public class Markice  implements java.io.Serializable {


     private Integer id;
     private Korisnik korisnik;
     private int godisnja;
     private int odobrena;
     private int obavesti;

    public Markice() {
    }

    public Markice(Korisnik korisnik, int godisnja, int odobrena, int obavesti) {
       this.korisnik = korisnik;
       this.godisnja = godisnja;
       this.odobrena = odobrena;
       this.obavesti = obavesti;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public int getGodisnja() {
        return this.godisnja;
    }
    
    public void setGodisnja(int godisnja) {
        this.godisnja = godisnja;
    }
    public int getOdobrena() {
        return this.odobrena;
    }
    
    public void setOdobrena(int odobrena) {
        this.odobrena = odobrena;
    }
    public int getObavesti() {
        return this.obavesti;
    }
    
    public void setObavesti(int obavesti) {
        this.obavesti = obavesti;
    }




}


