package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medjugradske generated by hbm2java
 */
public class Medjugradske  implements java.io.Serializable {


     private Integer id;
     private Autobusi autobusi;
     private Prevoznici prevoznici;
     private Vozaci vozaci;
     private String polaziste;
     private String odrediste;
     private String medjustanice;
     private Date polazak;
     private Date dolazak;
     private Set rezervacijas = new HashSet(0);

    public Medjugradske() {
    }

	
    public Medjugradske(Prevoznici prevoznici, String polaziste, String odrediste, String medjustanice) {
        this.prevoznici = prevoznici;
        this.polaziste = polaziste;
        this.odrediste = odrediste;
        this.medjustanice = medjustanice;
    }
    public Medjugradske(Autobusi autobusi, Prevoznici prevoznici, Vozaci vozaci, String polaziste, String odrediste, String medjustanice, Date polazak, Date dolazak, Set rezervacijas) {
       this.autobusi = autobusi;
       this.prevoznici = prevoznici;
       this.vozaci = vozaci;
       this.polaziste = polaziste;
       this.odrediste = odrediste;
       this.medjustanice = medjustanice;
       this.polazak = polazak;
       this.dolazak = dolazak;
       this.rezervacijas = rezervacijas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Autobusi getAutobusi() {
        return this.autobusi;
    }
    
    public void setAutobusi(Autobusi autobusi) {
        this.autobusi = autobusi;
    }
    public Prevoznici getPrevoznici() {
        return this.prevoznici;
    }
    
    public void setPrevoznici(Prevoznici prevoznici) {
        this.prevoznici = prevoznici;
    }
    public Vozaci getVozaci() {
        return this.vozaci;
    }
    
    public void setVozaci(Vozaci vozaci) {
        this.vozaci = vozaci;
    }
    public String getPolaziste() {
        return this.polaziste;
    }
    
    public void setPolaziste(String polaziste) {
        this.polaziste = polaziste;
    }
    public String getOdrediste() {
        return this.odrediste;
    }
    
    public void setOdrediste(String odrediste) {
        this.odrediste = odrediste;
    }
    public String getMedjustanice() {
        return this.medjustanice;
    }
    
    public void setMedjustanice(String medjustanice) {
        this.medjustanice = medjustanice;
    }
    public Date getPolazak() {
        return this.polazak;
    }
    
    public void setPolazak(Date polazak) {
        this.polazak = polazak;
    }
    public Date getDolazak() {
        return this.dolazak;
    }
    
    public void setDolazak(Date dolazak) {
        this.dolazak = dolazak;
    }
    public Set getRezervacijas() {
        return this.rezervacijas;
    }
    
    public void setRezervacijas(Set rezervacijas) {
        this.rezervacijas = rezervacijas;
    }




}


