package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Otkazane generated by hbm2java
 */
public class Otkazane  implements java.io.Serializable {


     private Integer id;
     private Gradske gradske;
     private Date periodOd;
     private Date periodDo;

    public Otkazane() {
    }

    public Otkazane(Gradske gradske, Date periodOd, Date periodDo) {
       this.gradske = gradske;
       this.periodOd = periodOd;
       this.periodDo = periodDo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Gradske getGradske() {
        return this.gradske;
    }
    
    public void setGradske(Gradske gradske) {
        this.gradske = gradske;
    }
    public Date getPeriodOd() {
        return this.periodOd;
    }
    
    public void setPeriodOd(Date periodOd) {
        this.periodOd = periodOd;
    }
    public Date getPeriodDo() {
        return this.periodDo;
    }
    
    public void setPeriodDo(Date periodDo) {
        this.periodDo = periodDo;
    }




}


