package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Prevoznici generated by hbm2java
 */
public class Prevoznici  implements java.io.Serializable {


     private Integer id;
     private String naziv;
     private String adresa;
     private String telefon;
     private String logo;
     private Set medjugradskes = new HashSet(0);

    public Prevoznici() {
    }

	
    public Prevoznici(String naziv, String adresa, String telefon) {
        this.naziv = naziv;
        this.adresa = adresa;
        this.telefon = telefon;
    }
    public Prevoznici(String naziv, String adresa, String telefon, String logo, Set medjugradskes) {
       this.naziv = naziv;
       this.adresa = adresa;
       this.telefon = telefon;
       this.logo = logo;
       this.medjugradskes = medjugradskes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public Set getMedjugradskes() {
        return this.medjugradskes;
    }
    
    public void setMedjugradskes(Set medjugradskes) {
        this.medjugradskes = medjugradskes;
    }




}


