package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1



/**
 * Redvoznje generated by hbm2java
 */
public class Redvoznje  implements java.io.Serializable {


     private Integer id;
     private Gradske gradske;
     private String polaziste;
     private String odrediste;
     private String polasci;

    public Redvoznje() {
    }

    public Redvoznje(Gradske gradske, String polaziste, String odrediste, String polasci) {
       this.gradske = gradske;
       this.polaziste = polaziste;
       this.odrediste = odrediste;
       this.polasci = polasci;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Gradske getGradske() {
        return this.gradske;
    }
    
    public void setGradske(Gradske gradske) {
        this.gradske = gradske;
    }
    public String getPolaziste() {
        return this.polaziste;
    }
    
    public void setPolaziste(String polaziste) {
        this.polaziste = polaziste;
    }
    public String getOdrediste() {
        return this.odrediste;
    }
    
    public void setOdrediste(String odrediste) {
        this.odrediste = odrediste;
    }
    public String getPolasci() {
        return this.polasci;
    }
    
    public void setPolasci(String polasci) {
        this.polasci = polasci;
    }




}


