package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1



/**
 * Rezervacija generated by hbm2java
 */
public class Rezervacija  implements java.io.Serializable {


     private Integer id;
     private Korisnik korisnik;
     private Medjugradske medjugradske;
     private String polaziste;
     private String odrediste;
     private int odobrena;
     private int obavesti;

    public Rezervacija() {
    }

    public Rezervacija(Korisnik korisnik, Medjugradske medjugradske, String polaziste, String odrediste, int odobrena, int obavesti) {
       this.korisnik = korisnik;
       this.medjugradske = medjugradske;
       this.polaziste = polaziste;
       this.odrediste = odrediste;
       this.odobrena = odobrena;
       this.obavesti = obavesti;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public Medjugradske getMedjugradske() {
        return this.medjugradske;
    }
    
    public void setMedjugradske(Medjugradske medjugradske) {
        this.medjugradske = medjugradske;
    }
    public String getPolaziste() {
        return this.polaziste;
    }
    
    public void setPolaziste(String polaziste) {
        this.polaziste = polaziste;
    }
    public String getOdrediste() {
        return this.odrediste;
    }
    
    public void setOdrediste(String odrediste) {
        this.odrediste = odrediste;
    }
    public int getOdobrena() {
        return this.odobrena;
    }
    
    public void setOdobrena(int odobrena) {
        this.odobrena = odobrena;
    }
    public int getObavesti() {
        return this.obavesti;
    }
    
    public void setObavesti(int obavesti) {
        this.obavesti = obavesti;
    }




}


