package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vozaci generated by hbm2java
 */
public class Vozaci  implements java.io.Serializable {


     private Integer id;
     private String ime;
     private String prezime;
     private Date datumRodj;
     private int iskustvo;
     private int slobodan;
     private Set medjugradskes = new HashSet(0);
     private Set vozigradskus = new HashSet(0);

    public Vozaci() {
    }

	
    public Vozaci(String ime, String prezime, Date datumRodj, int iskustvo, int slobodan) {
        this.ime = ime;
        this.prezime = prezime;
        this.datumRodj = datumRodj;
        this.iskustvo = iskustvo;
        this.slobodan = slobodan;
    }
    public Vozaci(String ime, String prezime, Date datumRodj, int iskustvo, int slobodan, Set medjugradskes, Set vozigradskus) {
       this.ime = ime;
       this.prezime = prezime;
       this.datumRodj = datumRodj;
       this.iskustvo = iskustvo;
       this.slobodan = slobodan;
       this.medjugradskes = medjugradskes;
       this.vozigradskus = vozigradskus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public Date getDatumRodj() {
        return this.datumRodj;
    }
    
    public void setDatumRodj(Date datumRodj) {
        this.datumRodj = datumRodj;
    }
    public int getIskustvo() {
        return this.iskustvo;
    }
    
    public void setIskustvo(int iskustvo) {
        this.iskustvo = iskustvo;
    }
    public int getSlobodan() {
        return this.slobodan;
    }
    
    public void setSlobodan(int slobodan) {
        this.slobodan = slobodan;
    }
    public Set getMedjugradskes() {
        return this.medjugradskes;
    }
    
    public void setMedjugradskes(Set medjugradskes) {
        this.medjugradskes = medjugradskes;
    }
    public Set getVozigradskus() {
        return this.vozigradskus;
    }
    
    public void setVozigradskus(Set vozigradskus) {
        this.vozigradskus = vozigradskus;
    }




}


