package beans;
// Generated Sep 22, 2018 4:10:50 PM by Hibernate Tools 4.3.1



/**
 * Vozigradsku generated by hbm2java
 */
public class Vozigradsku  implements java.io.Serializable {


     private Integer id;
     private Gradske gradske;
     private Vozaci vozaci;

    public Vozigradsku() {
    }

    public Vozigradsku(Gradske gradske, Vozaci vozaci) {
       this.gradske = gradske;
       this.vozaci = vozaci;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Gradske getGradske() {
        return this.gradske;
    }
    
    public void setGradske(Gradske gradske) {
        this.gradske = gradske;
    }
    public Vozaci getVozaci() {
        return this.vozaci;
    }
    
    public void setVozaci(Vozaci vozaci) {
        this.vozaci = vozaci;
    }




}


